export const ADD_GOOD_IN_CART = 'ADD_GOOD_IN_CART';
export const DELETE_GOOD_FROM_CART = 'DELETE_GOOD_FROM_CART';
export const DELETE_ALL_THIS_GOOD_FROM_CART = 'DELETE_ALL_THIS_GOOD_FROM_CART';
export const APPLY_DISCOUNT = 'APPLY_DISCOUNT';
export const SHOW_HAMBURGER = 'SHOW_HAMBURGER';
